name: Daily Bing Wallpaper

on:
  schedule:
    - cron: '0 16 * * *' 
workflow_dispatch:

jobs:
  fetch-wallpaper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install ImageMagick
        run: sudo apt-get install imagemagick

      - name: Download Bing wallpaper
        run: |
          IMAGE_URL=$(curl -s 'https://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1&mkt=zh-CN' | jq -r '.images[0].url')
          wget "https://www.bing.com$IMAGE_URL" -O bing_wallpaper.jpg

      - name: Resize and crop image to 1068x455 (bing_wx.jpg)
        run: |
          convert bing_wallpaper.jpg -resize 1068x455^ -gravity center -extent 1068x455 bing_wx.jpg

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add bing_wallpaper.jpg bing_wx.jpg
          git commit -m "Daily Bing Wallpaper Update $(date +'%Y-%m-%d')"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
